apiVersion: v2
name: gateway-api-chart
version: 1.1.8
appVersion: "0.0.1"
type: application
description: Deploy GKE gateway-api manifests as a sub-chart
keywords:
  - kubernetes
  - gateway-api
  - api gateway
  - httproute
  - gateway
  - serviceexport
  - serviceimport
  - service
  - multi-cluster
  - multi-cluster ingress
  - GKE
  - Google Kubernetes Engine
  - GCP
  - Google Cloud Platform
  - cloud armor
  - web application firewall
  - WAF
  - rate limiting
  - backend policy
  - gateway policy
  - health check
  - session affinity
  - connection draining
  - IAP
  - Identity-Aware Proxy
  - Config Connector
  - dependency chart
  - ingress alternative
  - gateway.networking.k8s.io
sources:
  - https://github.com/pursechicken/helm-charts