{{- if .Values.securityPolicy }}
{{- $allowResourceDeletion := .Values.allowResourceDeletion }}
{{- $projectName := include "cnrm-chart.projectID" . }}
{{- range .Values.securityPolicy }}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  annotations:
    {{- include "cnrm-chart.cnrmAnnotations" (dict "projectName" $projectName "allowResourceDeletion" $allowResourceDeletion) | nindent 4 }}
  name: {{ include "cnrm-chart.resourceName" (dict "projectName" $projectName "name" .name) }}
spec:
  resourceID: {{ .name }}
  description: {{ .description }}
  adaptiveProtectionConfig:
  {{- if .layer7DdosDefenseConfig }}
    layer7DdosDefenseConfig:
      enable: true
  {{- else }}
    layer7DdosDefenseConfig:
      enable: false
  {{- end }}
  type: {{ .type }}
  rule:
    {{- toYaml .rule | nindent 4 }}
{{- end -}}
{{- end -}}