apiVersion: v2
name: cnrm-chart
version: 1.3.9
appVersion: "0.0.1"
type: application
description: Deploy Projects and Infrastructure with Config Connector.
keywords:
  - kubernetes
  - cnrm
  - Config Connector
  - cnrm.cloud.google.com
sources:
  - https://github.com/pursechicken/helm-charts